### ISSUE TITLE
An error occurred { Error: binance {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}

### ISSUE THREAD

**Issue by robertmakrytski** [carlos8f/zenbot#1759]
### System information
- **Have I written custom code (as opposed to using zenbot vanilla)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
rig2@192:~/zenbot$ cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.5 LTS"
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
- **Zenbot version** (commit ref, or version): up-to-date
- **Zenbot branch**: master
- **NodeJS version**:nodejs -v v8.12.0
- **Python version (when using a python script)**:
- **Did I make any changes to conf-sample.js?**:
standart(app for binance and name for cryptocurrency

`sudo ./zenbot.sh trade
Error: Cannot find module './conf', falling back to conf-sample
(node:22057) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
fetching pre-roll data:
(node:22057) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
Error: Cannot find module './conf', falling back to conf-sample
(node:22069) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
(node:22069) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
(node:22069) DeprecationWarning: collection.save is deprecated. Use insertOne, insertMany, updateOne, or updateMany instead.

skipping 15 hrs of previously collected data

binance.ADA-BTC saved 500 trades 1 days left

binance.ADA-BTC saved 12 trades 0 days left

download complete!

               DATE            PRICE     DIFF       VOL     RSI                         ACTIONS                      BAL                PROFIT
2018-11-01 13:22:00  0.00001103 ADA-BTC             45741                             
2018-11-01 13:24:00  0.00001103 ADA-BTC   +0.00%     4163                             
------------------------------------------ INITIALIZE  OUTPUT ------------------------------------------
---------------------------------------- STARTING LIVE TRADING ----------------------------------------
Press  l  to list available commands.
Web GUI running on http://192.168.1.4:20070/
An error occurred { Error: binance {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}
    at binance.handleErrors (/home/rig2/zenbot/node_modules/ccxt/js/binance.js:1182:31)
    at response.text.then (/home/rig2/zenbot/node_modules/ccxt/js/base/Exchange.js:639:18)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7) constructor: [Function: InvalidNonce] }

Binance API is down! unable to call getBalance, retrying in 20s
[ { currency: 'BTC', asset: 'ADA' } ]
An error occurred { Error: binance {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}
    at binance.handleErrors (/home/rig2/zenbot/node_modules/ccxt/js/binance.js:1182:31)
    at response.text.then (/home/rig2/zenbot/node_modules/ccxt/js/base/Exchange.js:639:18)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7) constructor: [Function: InvalidNonce] }

Binance API is down! unable to call getBalance, retrying in 20s
[ { currency: 'BTC', asset: 'ADA' } ]
^C`
`timedatectl
      Local time: Thu 2018-11-01 13:31:11 +03
  Universal time: Thu 2018-11-01 10:31:11 UTC
        RTC time: Thu 2018-11-01 10:31:11
       Time zone: Europe/Minsk (+03, +0300)
 Network time on: no
NTP synchronized: yes
 RTC in local TZ: no
`

**Comment by robertmakrytski** [comment]
I live in the future. So the binance lives in the past. So i reconfig some parameter!
nano zenbot/node_modules/ccxt/js/binance.js
set parameter  'recvWindow': 15 * 1000, // 5 sec, binance default
it cost my one day, please add special message for this problem that people see correct message. I think that it can help!
