### ISSUE TITLE
Ichimoku_score: invalid bucket size spec: undefined

### ISSUE THREAD

**Issue by CuriouslyCory** [carlos8f/zenbot#1762]
### System information
- **Have I written custom code (as opposed to using zenbot vanilla)**: vanilla
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04.1 LTS as a Linux subsystem on Win 10
- **Zenbot version** (commit ref, or version): 
- **Zenbot branch**: Unstable & Master
- **NodeJS version**: 11.1.0
- **Python version (when using a python script)**:
- **Exact command to reproduce (include everything)**: zenbot sim gdax.BTC-USD --strategy ichimoku_score
- **Did I make any changes to conf-sample.js?**: added RO creds to conf.js

### Describe the problem
Running the command produces the following error. Other strats seem to run fine.

### Source code / Error logs
(node:4574) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
/mnt/d/workspace/zenbot/node_modules/timebucket/lib/bucket-size.js:15
  if (!match) throw new Error('invalid bucket size spec: ' + spec);
              ^

Error: invalid bucket size spec: undefined
    at BucketSize.parse (/mnt/d/workspace/zenbot/node_modules/timebucket/lib/bucket-size.js:15:21)
    at new BucketSize (/mnt/d/workspace/zenbot/node_modules/timebucket/lib/bucket-size.js:5:21)
    at Bucket.resize (/mnt/d/workspace/zenbot/node_modules/timebucket/lib/bucket.js:30:14)
    at Command.<anonymous> (/mnt/d/workspace/zenbot/commands/sim.js:98:49)
    at Command.listener (/mnt/d/workspace/zenbot/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:182:13)
    at Command.parseArgs (/mnt/d/workspace/zenbot/node_modules/commander/index.js:654:12)
    at Command.parse (/mnt/d/workspace/zenbot/node_modules/commander/index.js:474:21)
    at /mnt/d/workspace/zenbot/zenbot.js:46:13
    at FSReqCallback.oncomplete (fs.js:148:20)

**Comment by CuriouslyCory** [comment]
#resolved by adding parameters and adding them correctly
#original broken
zenbot sim gdax.BTC-USD --strategy ichimoku_score

#working corrected
zenbot sim gdax.BTC-USD --strategy="ichimoku_score" --days=15 --period="30m"
