### ISSUE TITLE
TherRockTrading Exchange problem

### ISSUE THREAD

**Issue by ziomik** [carlos8f/zenbot#1796]
Exchange Therocktrading not work:

```
ziomik@Debian-Bot:~/zenbot$ zenbot backfill therock.BTC-EUR
/home/ziomik/zenbot/node_modules/mongodb/lib/utils.js:132
      throw err;
      ^

Error: therock markets not loaded
    at therock.market (/home/ziomik/zenbot/node_modules/ccxt/js/base/Exchange.js:916:19)
    at Object.getTradesTheRock (/home/ziomik/zenbot/extensions/exchanges/therock/exchange.js:53:27)
    at Object.getTrades (/home/ziomik/zenbot/extensions/exchanges/therock/exchange.js:91:12)
    at getNext (/home/ziomik/zenbot/commands/backfill.js:83:18)
    at /home/ziomik/zenbot/commands/backfill.js:67:9
    at result (/home/ziomik/zenbot/node_modules/mongodb/lib/utils.js:414:17)
    at executeCallback (/home/ziomik/zenbot/node_modules/mongodb/lib/utils.js:406:9)
    at handleCallback (/home/ziomik/zenbot/node_modules/mongodb/lib/utils.js:128:55)
    at cursor.close (/home/ziomik/zenbot/node_modules/mongodb/lib/operations/cursor_ops.js:211:62)
    at handleCallback (/home/ziomik/zenbot/node_modules/mongodb/lib/utils.js:128:55)
```

**Comment by paci** [comment]
from a quick check, I found that on extensions/exchanges/therock/exchange.js client.market(args.id) seems not to work

with a quick workaround (let market = args.id) backfill seems to work for me

then I am unable to go further: without rate limiting (default), calling "zenbot trade therock.BTC-EUR" is a mess of 503 errors from ticker;

with rate limiting on, for reasons unknown to me, it seems to be able to update bid/ask but not last trade value until it throws an error about backlog at max capacity

**Comment by effelle** [comment]
Similar error here:
`./zenbot.sh trade selector=therock.BTC-EUR --paper --conf ./conf.js`
or simply
`./zenbot.sh trade therock.BTC-EUR`

```fetching pre-roll data:
/home/effe/zenbot/node_modules/mongodb/lib/utils.js:132
      throw err;
      ^

Error: therock markets not loaded
    at therock.market (/home/effe/zenbot/node_modules/ccxt/js/base/Exchange.js:986:19)
    at Object.getTradesTheRock (/home/effe/zenbot/extensions/exchanges/therock/exchange.js:53:27)
    at Object.getTrades (/home/effe/zenbot/extensions/exchanges/therock/exchange.js:91:12)
    at getNext (/home/effe/zenbot/commands/backfill.js:83:18)
    at /home/effe/zenbot/commands/backfill.js:67:9
    at result (/home/effe/zenbot/node_modules/mongodb/lib/utils.js:414:17)
    at executeCallback (/home/effe/zenbot/node_modules/mongodb/lib/utils.js:406:9)
    at handleCallback (/home/effe/zenbot/node_modules/mongodb/lib/utils.js:128:55)
    at cursor.close (/home/effe/zenbot/node_modules/mongodb/lib/operations/cursor_ops.js:224:62)
    at handleCallback (/home/effe/zenbot/node_modules/mongodb/lib/utils.js:128:55)

```
