### ISSUE TITLE
TypeError: Cannot read property 'open' of undefined

### ISSUE THREAD

**Issue by mikki155** [carlos8f/zenbot#1815]
### System information
- **Have I written custom code (as opposed to using zenbot vanilla)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **Zenbot version** (commit ref, or version): Zenbot 4
- **Zenbot branch**: Default
- **NodeJS version**: v8.15.0
- **Python version (when using a python script)**: 2.7.12
- **Exact command to reproduce (include everything)**: ./zenbot.sh trade
- **Did I make any changes to conf-sample.js?**: No

When I use the "neural" strategy, then all of a sudden I get the following error message:

```
/home/mikael/Documents/zenbot/extensions/strategies/neural/strategy.js:94
            x.set(0,0,k,data[k].open)
                                ^

TypeError: Cannot read property 'open' of undefined
    at predict (/home/mikael/Documents/zenbot/extensions/strategies/neural/strategy.js:94:33)
    at Object.onPeriod (/home/mikael/Documents/zenbot/extensions/strategies/neural/strategy.js:106:24)
    at onTrade (/home/mikael/Documents/zenbot/lib/engine.js:935:27)
    at /home/mikael/Documents/zenbot/lib/engine.js:913:5
    at /home/mikael/Documents/zenbot/node_modules/async/dist/async.js:4096:9
    at Object.process (/home/mikael/Documents/zenbot/node_modules/async/dist/async.js:2344:17)
    at /home/mikael/Documents/zenbot/node_modules/async/dist/async.js:2252:19
    at Immediate._onImmediate (/home/mikael/Documents/zenbot/node_modules/async/dist/async.js:119:16)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
```
I trade the pair ETH-BTC on Poloniex.

**Comment by wajakondijos** [comment]
I have go the same error.

**Comment by mnkprs** [comment]
Anyone identified the problem?

**Comment by kaldughayem** [comment]
It happens to me too when I set the depth to a higher value than 120
