### ISSUE TITLE
TypeError [ERR_INVALID_CALLBACK]: Callback must be a function

### ISSUE THREAD

**Issue by nonkreon** [carlos8f/zenbot#1857]
### System information
- instr on #1765 + zenbot vanilla
- Linux Mint 19 x64 XFCE
- Zenbot4 4.1.0
- master branch
- **NodeJS version**: v11.13.0
- **Python version (when using a python script)**: Python 2.7.15rc1
- **Exact command to reproduce (include everything)**:zenbot train --period 517m --days_training 90 --days_test 30 bittrex.ANT-BTC ; 
zenbot sim bittrex.ANT-BTC --strategy forex_analytics --modelfile /abs/path/to/modelfile.json --period 517m --min_periods 2

- **Did I make any changes to conf-sample.js?**: No

### Describe the problem
Training throws error, trying to use model aborts

### Source code / Error logs
Training ends with following:

```
(node:11633) DeprecationWarning: collection.save is deprecated. Use insertOne, insertMany, updateOne, or updateMany instead.
fs.js:141
    throw new ERR_INVALID_CALLBACK();
    ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at makeCallback (fs.js:141:11)
    at Object.rename (fs.js:594:14)
    at ChildProcess.<anonymous> (/home/poncik/zenbot/commands/train.js:285:16)
    at ChildProcess.emit (events.js:193:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:255:12)
```

Still trying to use generated model results in the following

`
0.00010521 ANT-BTC   +1.91%     7903                    terminate called after throwing an instance of 'char const*'
Aborted (core dumped)
`

**Comment by nonkreon** [comment]
Example model filename: forex.model_bittrex.WAX-BTC_period=517m_from=20181231_000000+0000_to=20190331_222300+0000_trainingVsBuyHold=-2.51_testVsBuyHold=noTest_created=20190331_234853+0000.json

The model filename is around 170 chars,but can the error still be somehing similar to [this](https://github.com/nodejs/node/issues/26188)? The model filename is extremely complex with dashes, dots, spaces and plus and equal signs which are controversial in my overly conservative file naming beliefs.

**Comment by mandaman2k** [comment]
Hi,

Did you found how to solve this? I'm having the same error
