### ISSUE TITLE
Binance API is down!

### ISSUE THREAD

**Issue by 1324qwer86** [carlos8f/zenbot#1868]
Help please. How can I solve this problem? Thanks for the help.
[ { currency: 'USDT', asset: 'BTC' } ]
An error occurred { Error: binance 429 Too Many Requests {"code":-1003,"msg":"Too many requests; current limit is 1200 requests per minute. Please use the websocket for live updates to avoid polling the API."}
    at binance.handleErrors (/root/zenbot/node_modules/ccxt/js/binance.js:1260:19)
    at response.text.then (/root/zenbot/node_modules/ccxt/js/base/Exchange.js:704:18)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7) constructor: [Function: DDoSProtection] }

**Comment by kenorb** [comment]
As per 'Too many requests', try less requests?

**Comment by 1324qwer86** [comment]
I’m sure that it’s about the frequency of sending requests. How can I fix this?

**Comment by ioapan** [comment]
> I’m sure that it’s about the frequency of sending requests. How can I fix this?

Hi, did you find how to solve this?
