### ISSUE TITLE
Docker on Windows 10 cannot find extensions folder . How to fix the Docker file for windows?

### ISSUE THREAD

**Issue by DooDiddle** [carlos8f/zenbot#1875]
Hello,

I have installed docker version, but it looks like mounts don't work . I think it's because the docker-compose-windows.yml file has someting in it. It says:
  volumes:
    - ./conf.js:/app/conf.js
    - ./extensions:/app/extensions

Which give me these erros because I think it can't find these files.
Attaching to zenbot_mongodb-data_1, zenbot_mongodb_1, zenbot_server_1
[36mzenbot_mongodb-data_1 exited with code 0
[0m[32mserver_1        |[0m Error: Cannot find module './conf', falling back to conf-sample
[32mserver_1        |[0m WARNING: MongoDB Connection Error:  { MongoNetworkError: failed to connect to server [172.17.0.3:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 172.17.0.3:27017]
[32mserver_1        |[0m     at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:564:11)
[32mserver_1        |[0m     at emitOne (events.js:116:13)
[32mserver_1        |[0m     at Pool.emit (events.js:211:7)
[32mserver_1        |[0m     at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:317:12)
[32mserver_1        |[0m     at Object.onceWrapper (events.js:317:30)
[32mserver_1        |[0m     at emitTwo (events.js:126:13)
[32mserver_1        |[0m     at Connection.emit (events.js:214:7)
[32mserver_1        |[0m     at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:246:50)
[32mserver_1        |[0m     at Object.onceWrapper (events.js:315:30)
[32mserver_1        |[0m     at emitOne (events.js:116:13)
[32mserver_1        |[0m   name: 'MongoNetworkError',
[32mserver_1        |[0m   errorLabels: [ 'TransientTransactionError' ],
[32mserver_1        |[0m   [Symbol(mongoErrorContextSymbol)]: {} }
[32mserver_1        |[0m WARNING: without MongoDB some features (such as backfilling/simulation) may be disabled.
[32mserver_1        |[0m Attempted authentication string: mongodb://172.17.0.3:27017/zenbot4?
[32mserver_1        |[0m module.js:550
[32mserver_1        |[0m     throw err;
[32mserver_1        |[0m     ^
[32mserver_1        |[0m 
[32mserver_1        |[0m Error: Cannot find module '/app/extensions/exchanges/sim/exchange'
[32mserver_1        |[0m     at Function.Module._resolveFilename (module.js:548:15)
[32mserver_1        |[0m     at Function.Module._load (module.js:475:25)
[32mserver_1        |[0m     at Module.require (module.js:597:17)
[32mserver_1        |[0m     at require (internal/module.js:11:18)
[32mserver_1        |[0m     at module.exports (/app/lib/engine.js:29:20)
[32mserver_1        |[0m     at Command.<anonymous> (/app/commands/trade.js:102:20)
[32mserver_1        |[0m     at Command.listener (/app/node_modules/commander/index.js:315:8)
[32mserver_1        |[0m     at emitTwo (events.js:126:13)
[32mserver_1        |[0m     at Command.emit (events.js:214:7)
[32mserver_1        |[0m     at Command.parseArgs (/app/node_modules/commander/index.js:654:12)
[32mzenbot_server_1 exited with code 1
[0m[33mzenbot_mongodb_1 exited with code 0
[0m

**Comment by DooDiddle** [comment]
server_1        | Error: Cannot find module './conf', falling back to conf-sample                      │        C:\projects\localtalking\platforms\android\app\build\outputs\apk\release\app-release.apk
server_1        | module.js:550                                                                        │Checking Java JDK and Android SDK versions
server_1        |     throw err;

**Comment by DooDiddle** [comment]
I tried to use just the docker-compose.yml file on my windows. It looks like it went though whole bunch of things, but then gave this error (a different one). What's the difference between the two yml files that's causing different errors?

ERROR: for zenbot_server_1  Cannot start service server: OCI runtime create failed: container_linux.go:
348: starting container process caused "exec: \"/app/zenbot.sh\": stat /app/zenbot.sh: no such file or │$ pwd
directory": unknown                                                                                   
                                                                                                       │
ERROR: for server  Cannot start service server: OCI runtime create failed: container_linux.go:348: 
ting container process caused "exec: \"/app/zenbot.sh\": stat /app/zenbot.sh: no such file or directory│$
": unknown

**Comment by DooDiddle** [comment]
Any help by any chance? Do you need more info?
