### ISSUE TITLE
No response with GDAX on SELL

### ISSUE THREAD

**Issue by bsesic** [carlos8f/zenbot#1906]
### System information
- **Have I written custom code (as opposed to using zenbot vanilla)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **Zenbot version** (commit ref, or version): e9b60446d7d575cd5a0232ebff5a6b2609865128
- **Zenbot branch**: unstable
- **NodeJS version**: v10.16.0
- **Python version (when using a python script)**:
- **Exact command to reproduce (include everything)**: ./zenbot.sh sell
- **Did I make any changes to conf-sample.js?**: yes

### Describe the problem
When I am trying to sell manually with gdax, the sale is not.
The response is empty and cannot be read.

### Source code / Error logs
/home/benni/zenbot/extensions/exchanges/gdax/exchange.js:495
        if (resp.statusCode === 404) {
                 ^

TypeError: Cannot read property 'statusCode' of undefined
    at /home/benni/zenbot/extensions/exchanges/gdax/exchange.js:495:18
    at Request._callback (/home/benni/zenbot/node_modules/gdax/lib/clients/public.js:81:11)
    at Request.self.callback (/home/benni/zenbot/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/home/benni/zenbot/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/home/benni/zenbot/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by ssepa001** [comment]
Hi bsesic, 

the GDAX npm package is now deprecated. I am working on getting the new coinbase-pro package to work.

**Comment by DeviaVir** [comment]
PR has been merged! Feel free to re-open if you still have this issue.

**Comment by bsesic** [comment]
It works, thanks!
