### ISSUE TITLE
"no trades found" using sim, after backfill

### ISSUE THREAD

**Issue by RedCellSh** [carlos8f/zenbot#1917]
System information
- **Have I written custom code (as opposed to using zenbot vanilla)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Debian 9, Docker
- **Zenbot version** (commit ref, or version): 4.1.0 (Latest docker container)
- **Zenbot branch**: Latest Docker
- **NodeJS version**: Latest Docker
- **Python version (when using a python script)**: Latest docker
- **Exact command to reproduce (include everything)**: docker-compose exec server zenbot sim
- **Did I make any changes to conf-sample.js?**: c.selector = 'kraken.ADA-ZEUR'

### Describe the problem
After a backfill `docker-compose exec server zenbot backfill kraken.ADA-EUR`, running `docker-compose exec server zenbot sim` fails with `no trades found! try running zenbot backfill kraken.ADA-ZEUR first`

The command `docker-compose exec server zenbot backfill kraken.ADA-ZEUR` fails with
```
Trades error:
Error: Query:Unknown asset pair
    at rawRequest (/app/node_modules/kraken-api/kraken.js:54:9)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)

getTrades() returned no trades, retrying with smaller interval.

```
It looks like there is a mismatch between backfill (ZEUR) and sim (EUR). Same problem with ZUSD vs USD.

**Comment by ZeroCool940711** [comment]
I'm having the same problem with Kraken, because of how long your issue have been open I assume this will never be fixed, if you did manage to make it work please let me know, I would like to use zenbot on kraken but it doesn't seem to work no matter what I do.
