### ISSUE TITLE
Backfill using Kraken results in timeouts

### ISSUE THREAD

**Issue by Blacksheep70** [carlos8f/zenbot#2278]
### System information

- **OS**:Linux Mint 20 Ulyana (Ubuntu focal)
- **Zenbot version** : 4.1.0
- **Zenbot branch**:  unstable
- **NodeJS version**: v10.19.0
- **Python version (when using a python script)**: 3.7.7
- **Exact command to reproduce (include everything)**: ./zenbot.sh backfill kraken.XXBT-ZEUR -d 14
- **Did I make any changes to conf-sample.js?**: Only exchange

### Describe the problem
Backfilling using Kraken exchange results in timeouts

### Source code / Error logs
```
(base) mmarre@mmarre-VirtualBox:~/zenbot$ ./zenbot.sh backfill kraken.XXBT-ZEUR -d 14

skipping 93 hrs of previously collected data

kraken.XXBT-ZEUR saved 1000 trades 11 days left

Trades error:
{ RequestError: Timeout awaiting 'request' for 5000ms
    at ClientRequest.request.once (/home/mmarre/zenbot/node_modules/kraken-api/node_modules/got/dist/source/core/index.js:785:25)
    at Object.onceWrapper (events.js:286:20)
    at ClientRequest.emit (events.js:203:15)
    at ClientRequest.origin.emit.args (/home/mmarre/zenbot/node_modules/kraken-api/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
    at TLSSocket.socketErrorListener (_http_client.js:401:9)
    at TLSSocket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Timeout.timeoutHandler (/home/mmarre/zenbot/node_modules/kraken-api/node_modules/got/dist/source/core/utils/timed-out.js:35:25)
    at ontimeout (timers.js:438:13)
    at tryOnTimeout (timers.js:300:5)
    at unrefdHandle (timers.js:520:7)
    at Timer.processTimers (timers.js:222:12)
  name: 'TimeoutError',
  code: 'ETIMEDOUT',
  timings:
   { start: 1595092179284,
     socket: 1595092179284,
     lookup: 1595092179285,
     connect: 1595092179294,
     secureConnect: 1595092179310,
     upload: 1595092179284,
     response: 1595092179569,
     end: undefined,
     error: 1595092184287,
     abort: undefined,
     phases:
      { wait: 0,
        dns: 1,
        tcp: 9,
        tls: 16,
        request: NaN,
        firstByte: 285,
        download: undefined,
        total: 5003 } },
  event: 'request',
  bufferedData:
   <Buffer 7b 22 65 72 72 6f 72 22 3a 5b 5d 2c 22 72 65 73 75 6c 74 22 3a 7b 22 58 58 42 54 5a 45 55 52 22 3a 5b 5b 22 38 33 34 34 2e 33 30 30 30 30 22 2c 22 30 ... > }

download complete!
```
It's known that Kraken is having a crappy API which is happy to run into timeouts. However, I suggest to work around this by running in a loop for backfill, just printing a warning when a timeout occur and continue to download until all data requested is being downloaded or a real error occur.

In any case "download complete!" is wrong here as it has been aborted earlier.

**Comment by yellowgh0st** [comment]
Increase poll times to fit your needs. These settings work without timeouts for me:

```
// ms to poll order status
c.order_poll_time = process.env.ZENBOT_ORDER_POLL_TIME || 5500
// ms to wait for settlement (after an order cancel)
c.wait_for_settlement = process.env.ZENBOT_WAIT_FOR_SETTLEMENT || 5000

// defaults to a high number of lookback periods
c.keep_lookback_periods = process.env.ZENBOT_KEEP_LOOKBACK_PERIODS || 50000
// ms to poll new trades at
c.poll_trades = process.env.ZENBOT_POLL_TRADES || 30000
```

**Not a bug.**
