### ISSUE TITLE
How to install ZenBot without any errors or warnings?

### ISSUE THREAD

**Issue by oObelix** [carlos8f/zenbot#2597]
All attempts to install it with `npm install` with mongoldb 3.-4. or node 8.x,10.x,15.x returns lot of errors and deprecations. What is the best solution to get clean installation? Maybe someone have a preinstalled node modules and compatible node version for them? Also same for Docker installation.

**Comment by dannoso** [comment]
I really hope this will be fixed because it is unusable like this. The main reason is the very old forex.analytic module but there are also other warning around. 
This might make the difference between a dead or alive project.

**Comment by oObelix** [comment]
In my case is nothing working: `sim` trade return error, `paper` trade is add just first buy and hold it always with any aggressive bot settings..
I learn browser JS more than 10 years ago, but I don't understand modern node to fix this. I have no idea how to support node projects with current situation with module updates and incompatibility! I hope someone can put this code in order.

**Comment by dannoso** [comment]
I made it work using the node version 10.23.0 with `sudo n 10.23.0` but after that the backfill hung up forever.... So I gave up.

**Comment by ndasim** [comment]
As a zenbot veteran installer, let me give you full install script for ubuntu 18.04:

```
sudo apt-get update
sudo apt-get install build-essential -y
sudo apt install curl -y
curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
sudo apt install nodejs -y
curl -fsSL https://www.mongodb.org/static/pgp/server-4.4.asc | sudo apt-key add -
echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.4.list
sudo apt update
sudo apt install mongodb-org -y

## This can vary with your system, 
## there are opsions for running mondog on service, 
## if still not working than just run mongod on the tmux :D 
sudo systemctl start mongod.service
sudo systemctl enable mongod
git clone https://github.com/DeviaVir/zenbot.git
cd zenbot/
npm install -g node-gyp

## !! READ THIS
## Before installing packages goto package.json and change 
## webpack and webpack-cli versions as ^4.0.0
npm install
./node_modules/webpack/bin/webpack.js  # This one also funny because post-install.js tries to run webpack with -p :D 

## Also tulind some times not installing well, you need to go
## Its folder and try npm install: 
cd node-packages/tulind/;npm install
```

I didn't run above script in one go, but I installed new machine a couple hour ago and used above codes. Some lines can be mistyped or mistaken. But idea is simple: install node 10.x, install mongo(if service not fires, run in tmux), install zenbot, change webpack version to 4.x, run webpack again (without -p ofcouse xD). Then just run `./zenbot.sh trade --paper` :)

nodejs environment really too stressful, I tried several versions to achieve best fit. 
Also my approach on install works for the windows, talib libraries starting to fight with your VS builder :D a full install of VS2019 build environment (nearly 6GB!) fixed this issue well.

**Comment by hliebscher** [comment]
i fix it with npx webpack --progress   insted of webpack -

**Comment by ChairmenMeow100** [comment]
hey @ndasim , thanks for your guide. I have followed it but unfortunately i get some errors and i am too unskilled to fix it - maybe you could help me? (error shown below) 

npm install

> zenbot4@4.1.0 postinstall /home/blacktop_ubuntu/zenbot
> node post_install.js

bundling WebApp components
[webpack-cli] Error: No loader specified
    at Function.normalizeUseItem (/home/blacktop_ubuntu/zenbot/node_modules/webpack/lib/RuleSet.js:389:10)
    at Function.normalizeUse (/home/blacktop_ubuntu/zenbot/node_modules/webpack/lib/RuleSet.js:360:19)
    at use.map (/home/blacktop_ubuntu/zenbot/node_modules/webpack/lib/RuleSet.js:357:33)
    at Array.map (<anonymous>)
    at Function.normalizeUse (/home/blacktop_ubuntu/zenbot/node_modules/webpack/lib/RuleSet.js:357:6)
    at Function.normalizeRule (/home/blacktop_ubuntu/zenbot/node_modules/webpack/lib/RuleSet.js:288:26)
    at rules.map (/home/blacktop_ubuntu/zenbot/node_modules/webpack/lib/RuleSet.js:110:20)
    at Array.map (<anonymous>)
    at Function.normalizeRules (/home/blacktop_ubuntu/zenbot/node_modules/webpack/lib/RuleSet.js:109:17)
    at new RuleSet (/home/blacktop_ubuntu/zenbot/node_modules/webpack/lib/RuleSet.js:104:24)
    at new NormalModuleFactory (/home/blacktop_ubuntu/zenbot/node_modules/webpack/lib/NormalModuleFactory.js:115:18)
    at Compiler.createNormalModuleFactory (/home/blacktop_ubuntu/zenbot/node_modules/webpack/lib/Compiler.js:636:31)
    at Compiler.newCompilationParams (/home/blacktop_ubuntu/zenbot/node_modules/webpack/lib/Compiler.js:653:30)
    at Compiler.compile (/home/blacktop_ubuntu/zenbot/node_modules/webpack/lib/Compiler.js:661:23)
    at readRecords.err (/home/blacktop_ubuntu/zenbot/node_modules/webpack/lib/Compiler.js:321:11)
    at Compiler.readRecords (/home/blacktop_ubuntu/zenbot/node_modules/webpack/lib/Compiler.js:529:11)
    at hooks.run.callAsync.err (/home/blacktop_ubuntu/zenbot/node_modules/webpack/lib/Compiler.js:318:10)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/blacktop_ubuntu/zenbot/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/home/blacktop_ubuntu/zenbot/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.beforeRun.callAsync.err (/home/blacktop_ubuntu/zenbot/node_modules/webpack/lib/Compiler.js:315:19)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/blacktop_ubuntu/zenbot/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/home/blacktop_ubuntu/zenbot/node_modules/tapable/lib/Hook.js:154:20)
installing genetic_backtester components
npm WARN zenbot4_auto_backtester@0.2.0 No repository field.
npm WARN zenbot4_auto_backtester@0.2.0 No license field.

audited 46 packages in 1.317s

5 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities


> zenbot4@4.1.0 prepare /home/blacktop_ubuntu/zenbot
> npm run snyk-protect


> zenbot4@4.1.0 snyk-protect /home/blacktop_ubuntu/zenbot
> snyk protect

Successfully applied Snyk patches

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.1 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

audited 2244 packages in 39.769s

84 packages are looking for funding
  run `npm fund` for details

found 8 vulnerabilities (2 low, 1 moderate, 5 high)
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by ChairmenMeow100** [comment]
I have found my Problem - i have downgraded the webpack and webpack-cli version as you mentioned - but in the meantime this was fixed. I have reinstalled it withe the right webpack and now it runs as expected.

**Comment by ben9583** [comment]
Yep, I ran through the guide and got this same error; changing back to webpack ^5.0.0 solved the issue.
