### ISSUE TITLE
Kraken Exchange ZEUR price can only be specified up to 1 decimals.

### ISSUE THREAD

**Issue by hliebscher** [carlos8f/zenbot#2645]
### System information
-  MAC OSX:
- **Zenbot version** (fix: broken kraken products #2641):

### Describe the problem
Kraken Exchange ZEUR price can only be specified up to 1 decimals.

### Source code / Error logs
order rejected
    at /Users/hliebscher/opt/zenbot/lib/engine.js:301:15
    at /Users/hliebscher/opt/zenbot/extensions/exchanges/kraken/exchange.js:283:20
    at response.then.catch (/Users/hliebscher/opt/zenbot/node_modules/kraken-api/kraken.js:176:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  order:
   { id: null,
     status: 'rejected',
     price: '39995.8020000000',
     size: '0.00187609',
     created_at: 1613340911210,
     filled_size: '0',
     post_only: true,
     reject_reason:
      'Order:Invalid price:XXBTZEUR price can only be specified up to 1 decimals.' },
  desc: 'could not execute buy: error placing order' }

**Comment by hliebscher** [comment]
Hi 
i find out this is only when i use option --markup_sell_pct or --markup_buy_pct  
without it works !
