### ISSUE TITLE
KRAKEN API rejecting orders with prices value >5 decimals

### ISSUE THREAD

**Issue by Pistol-Peet** [carlos8f/zenbot#2661]
### System information
- **Have I written custom code (as opposed to using zenbot vanilla)**: No
- **OS Platform and Distribution: ubuntu 20.04
- **Zenbot version** (commit ref, or version): 4.1.0
- **Zenbot branch**: unstable
- **NodeJS version**: 14.16.0-deb-1
- **Python version (when using a python script)**: python3.8
- **Exact command to reproduce (include everything)**: zenbot trade kraken.DAI-EUR --strategie trendline
- **Did I make any changes to conf-sample.js?**: yes (minor)

### Describe the problem
When running trades through KrakenAPI ordeers with a pricedecimal >5 are being rejected

### Source code / Error logs
![image](https://user-images.githubusercontent.com/71960913/109385358-6f064500-78f3-11eb-9ef5-3261011a7198.png)
// cleartext
Unhandeld AddOrder error:
Error: Order:Invalid price:DAIEUR price can only be specified up to 5 decimals.
    at rawRequest (/root/zenbot/node_modules/kraken-api/kraken.js:54:9)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

Error: 
order rejected
    at /root/zenbot/lib/engine.js:301:15
    at /root/zenbot/extensions/exchanges/kraken/exchange.js:283:20
    at /root/zenbot/node_modules/kraken-api/kraken.js:176:23
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  order: {
    id: null,
    status: 'rejected',
    price: '0.8577943000',
    size: '13.88920844',
    created_at: 1614420044429,
    filled_size: '0',
    post_only: false,
    reject_reason: 'Order:Invalid price:DAIEUR price can only be specified up to 5 decimals.'
  },
  desc: 'could not execute sell: error placing order'

**Comment by tommyyama2020** [comment]
@Pistol-Peet  Just out of curiosity, you can not use a currency with five decimal places for the asset pair?  I am" just" curious.
Public API says so. ![image](https://user-images.githubusercontent.com/38548157/109674909-a65a4780-7bba-11eb-9f00-66a6d4a25728.png)

**Comment by Pistol-Peet** [comment]
According to the screenshot I couldn´t.
The order came out like this 
![image](https://user-images.githubusercontent.com/71960913/110329529-03238b00-801d-11eb-8542-b46de0d88b32.png)
So that might have triggered the warning. Hence caused the rejection.
Question is, when defining the pair decimals as you show in your screenshot, does zenbot consider it for the calculation of orders?
