### ISSUE TITLE
kraken: order buy XETH-ZEUR and XXRP-ZEUR 

### ISSUE THREAD

**Issue by carbone07** [carlos8f/zenbot#2690]
### System information
- **Have I written custom code (as opposed to using zenbot vanilla)**: no
- **OS centos server 7**:
- **Zenbot version** (commit ref, or version):  4.1.0
- **Zenbot branch**: unstable
- **NodeJS version**: v14.17.0
- **Python version (when using a python script)**:  2.7.5
- **Exact command to reproduce (include everything)**:  ./zenbot.sh trade kraken.XETH-ZEUR
- **Did I make any changes to conf-sample.js?**: only keys for kraken

### Describe the problem
the order of but not are executed for next error 'Error: General:Invalid arguments'
i have the the same error for couple XXRP-ZEUR 

### Source code / Error logs
Unhandeld AddOrder error:
Error: General:Invalid arguments
    at rawRequest (/opt/zenbot/node_modules/kraken-api/kraken.js:54:9)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

Error:
order rejected
    at /opt/zenbot/lib/engine.js:301:15
    at /opt/zenbot/extensions/exchanges/kraken/exchange.js:283:20
    at /opt/zenbot/node_modules/kraken-api/kraken.js:176:23
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  order: {
    id: null,
    status: 'rejected',
    price: '2302.9700000000',
    size: '0.15539231',
    created_at: 1622065493915,
    filled_size: '0',
    post_only: true,
    reject_reason: 'General:Invalid arguments'
  },
  desc: 'could not execute buy: error placing order'
}

**Comment by carbone07** [comment]
hi guys i solved the problem on my local copy by checking the kraken documentation and doing some tests
I encountered the problem in a parameter that was passed in the addOrder function in the file "../zenbot/extensions/exchanges/exchange.js" on line 234 (trading_agreement: conf.kraken.tosagree)

I just commented out the line and now I order it to be executed.

not knowing the project in detail I leave you the correction on the sources,
 hello 

![immagine](https://user-images.githubusercontent.com/4214833/119902061-060c8880-bf47-11eb-86ed-7390403ec243.png)
